# Generated by Django 3.1.4 on 2020-12-29 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0002_auto_20201228_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Bebida',
            new_name='bebida',
        ),
    ]
