# Generated by Django 3.1.4 on 2020-12-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_auto_20201229_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bebida',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='preco_compra',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantidade',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
