# Generated by Django 3.1.4 on 2021-01-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0004_auto_20201230_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='bebida',
            field=models.CharField(blank=True, choices=[('Brahma', 'Brahma'), ('Skol', 'Skol'), ('Glacial', 'Glacial')], max_length=50, null=True),
        ),
    ]
