# Generated by Django 3.1.4 on 2021-01-03 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0005_auto_20210103_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bebida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.bebida'),
            preserve_default=False,
        ),
    ]
