# Generated by Django 3.1.4 on 2021-01-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0007_auto_20210103_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='erro_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='reportar_erro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
