# Generated by Django 3.1.4 on 2021-01-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_auto_20210127_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='recebido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='recebido_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
