# Generated by Django 3.1.4 on 2021-01-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0009_auto_20210127_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='recebido',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reportar_erro',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
