# Generated by Django 3.1.4 on 2021-08-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0011_stock_reorder_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bebida',
            new_name='Nome_relatorio',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='erro_por',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='recebido_por',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='bebida',
            new_name='nome_relatorio',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='data_recebimento',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='preco_compra',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='recebido',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='stock',
            name='sob_supervisao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
