# Generated by Django 3.1.4 on 2021-08-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0012_auto_20210823_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tipo_relatorio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='descricao',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
