# Generated by Django 3.1.4 on 2021-08-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0013_auto_20210823_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='link',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
    ]
