# Generated by Django 3.1.4 on 2021-08-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0014_auto_20210824_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nome_relatorio',
            new_name='Tipo_relatorio',
        ),
    ]
