# Generated by Django 3.1.4 on 2021-08-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0015_auto_20210824_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='nome_relatorio',
        ),
    ]
