# Generated by Django 3.1.4 on 2021-08-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0016_remove_stock_nome_relatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='tipo_relatorio',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stockmgmt.tipo_relatorio'),
        ),
    ]
