# Generated by Django 3.1.4 on 2021-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0017_auto_20210824_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='nome_relatorio',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
